### ISSUE TITLE
Failed to build on RN 0.17

### ISSUE THREAD

**Issue by eyaleizenberg** [chirag04/react-native-tooltip#5]
Getting RCTSparseArray.h file not found. It looks like RN dropped it. 
https://github.com/facebook/react-native/commit/fa0b45c58b248bad33a339484ac83aaf757c831d

Any chance for an update?

**Comment by chirag04** [comment]
I'm on vacation till 28th Dec. I will update this on 29th. Happy to accept a PR.

**Comment by eyaleizenberg** [comment]
This fork has done it already:
https://github.com/taskrabbit/react-native-tooltip

**Comment by chirag04** [comment]
@jrichardlai seems like you made some interesting changes in your fork. Seems like you tweaked the JS api as well. can you describe the changes here and eventually merge the two codebases if it works out?

**Comment by jrichardlai** [comment]
@chirag04 I have done some update to the api yes. Thank you for this library it is really useful.
The use case I was trying to do was mosty having a long press on a view and being able to copy it.

<img width="255" alt="screen shot 2015-12-23 at 8 42 18 am" src="https://cloud.githubusercontent.com/assets/159813/11980655/67e4de20-a951-11e5-9ebc-7a59b84d52e2.png">

I wanted it to be able to create a tooltip on any element, you can put the tooltip around `View` and `Image`.

I also wanted to make only one component to use. And it seemed easier in our case to just pass down directly the callback instead of checking the value of the text clicked.

For example you could do this:

``` javascript
class Message extends React.Component {

  handleCopyPress = () => {
    Clipboard.set('Something something');
  }

  handleSendSMSPress = () => {
    alert('Sending SMS');
  }

  render() {
    return (
      <ToolTip
        actions={[
          {text: 'Copy', onPress: this.handleCopyPress},
          {text: 'Send By SMS', onPress: this.handleSendSMSPress},
        ]}
        underlayColor={cssVar('trGreen10')}
        longPress={true}
      >
        <Text>Something something</Text>
      </ToolTip>
    );
  }
}
```

I removed the `ToolTipText` component, since it was redundant with the `Tooltip` but I can keep it and make a PR if you'd like.

**Comment by eyaleizenberg** [comment]
@jrichardlai For some reason you fork doesn't work for me in RN 0.17
I am hit with: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

This is my code:

``` coffeescript
<ToolTip
  actions={[
    {text: 'x', onPress: () => console.log("X") }
    {text: 'y', onPress: () => console.log("Y") }
  ]}
  underlayColor={'blue'}
  style={textElements.selectedName}
>
  <Text>
    {user.name}
  </Text>
</ToolTip>
```

it seems that in your ToolTop.ios.js file you need to write in the end: `module.exports = ToolTipText`

Sorry for posting this here but I couldn't find the 'issues' tab in your fork

**Comment by jrichardlai** [comment]
@eyaleizenberg thanks let me fix this :)

**Comment by jrichardlai** [comment]
@eyaleizenberg seems to work fine for me, I added an Example App you can take a look

**Comment by jrichardlai** [comment]
@eyaleizenberg @chirag04 any news?

**Comment by ghost** [comment]
@jrichardlai, @chirag04, I think the changes jrichardlai made are great additions to the component. I would suggest merging the changes back into the main project, although I would keep things ES5 compatible like it is today. Any objections?

**Comment by chirag04** [comment]
No objections. @jrichardlai @sevachb Can one of you PR?

**Comment by chirag04** [comment]
we merged the two codebases. It should be fixed on master now.
